import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  tenants: defineTable({
    name: v.string(),
    slug: v.string(),
    timezone: v.string(),
    contactEmail: v.string(),
    notificationEmails: v.array(v.string()),
    hoursOfOperation: v.string(),
    logoStorageId: v.optional(v.id("_storage")),
    uploadMaxBytes: v.number(),
    workosOrganizationId: v.optional(v.string()),
  }).index("by_slug", ["slug"]).index("by_workos_org", ["workosOrganizationId"]),
  users: defineTable({
    tenantId: v.id("tenants"),
    workosUserId: v.string(),
    email: v.string(),
    name: v.string(),
    role: v.union(v.literal("Admin"), v.literal("Staff"), v.literal("Requester")),
  }).index("by_tenant_role", ["tenantId", "role"]).index("by_workos_user", ["workosUserId"]).index("by_tenant_email", ["tenantId", "email"]),
  campuses: defineTable({
    tenantId: v.id("tenants"),
    name: v.string(),
  }).index("by_tenant", ["tenantId"]),
  roomTypes: defineTable({
    tenantId: v.id("tenants"),
    campusId: v.optional(v.id("campuses")),
    name: v.string(),
    maxDurationHours: v.number(),
    capacity: v.number(),
    quantity: v.number(),
    isSpecial: v.boolean(),
  }).index("by_tenant", ["tenantId"]),
  rooms: defineTable({
    tenantId: v.id("tenants"),
    roomTypeId: v.id("roomTypes"),
    code: v.string(),
    name: v.string(),
    active: v.boolean(),
  }).index("by_tenant_type", ["tenantId", "roomTypeId"]),
  bookingRequests: defineTable({
    tenantId: v.id("tenants"),
    requesterUserId: v.optional(v.id("users")),
    requesterName: v.string(),
    requesterEmail: v.string(),
    requesterPhone: v.optional(v.string()),
    sessionName: v.string(),
    attendeeCount: v.number(),
    details: v.string(),
    ccEmails: v.array(v.string()),
    status: v.union(v.literal("Pending"), v.literal("Approved"), v.literal("Completed"), v.literal("Declined"), v.literal("Cancelled")),
    timezone: v.string(),
    blocks: v.array(v.object({ label: v.union(v.literal("Setup"), v.literal("Session"), v.literal("Cleanup")), start: v.string(), end: v.string() })),
    roomTypeRequests: v.array(v.object({ roomTypeId: v.id("roomTypes"), quantity: v.number() })),
    assignedRoomIds: v.array(v.id("rooms")),
    customInputs: v.array(v.object({ fieldId: v.string(), label: v.string(), value: v.any() })),
    attachmentStorageIds: v.array(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_tenant_status", ["tenantId", "status"]).index("by_tenant_created", ["tenantId", "createdAt"]),
  comments: defineTable({
    tenantId: v.id("tenants"),
    requestId: v.id("bookingRequests"),
    authorUserId: v.optional(v.id("users")),
    bodyMarkdown: v.string(),
    internal: v.boolean(),
    createdAt: v.number(),
  }).index("by_request", ["requestId"]),
  notifications: defineTable({
    tenantId: v.id("tenants"),
    userId: v.optional(v.id("users")),
    requestId: v.optional(v.id("bookingRequests")),
    message: v.string(),
    seen: v.boolean(),
    createdAt: v.number(),
  }).index("by_tenant_seen", ["tenantId", "seen"]).index("by_user_seen", ["userId", "seen"]),
  formConfigs: defineTable({
    tenantId: v.id("tenants"),
    fileUploadEnabled: v.boolean(),
    fields: v.array(v.object({
      id: v.string(),
      label: v.string(),
      type: v.union(v.literal("text"), v.literal("number"), v.literal("textarea"), v.literal("radio"), v.literal("select"), v.literal("divider"), v.literal("note"), v.literal("checkboxGroup")),
      required: v.boolean(),
      helpText: v.optional(v.string()),
      options: v.optional(v.array(v.string())),
    })),
  }).index("by_tenant", ["tenantId"]),
  blockedTimes: defineTable({
    tenantId: v.id("tenants"),
    roomId: v.optional(v.id("rooms")),
    start: v.string(),
    end: v.string(),
    reason: v.string(),
  }).index("by_tenant", ["tenantId"]),
});
